ui fixes
charlescohanlon/ProfesScore pull request #3
Opened 2022-11-14 21:19 UTC by KingMedieval

fixes an issue where contact page gets cut off on some devices. It also adds a bottom border to ResultScrollView.tsx that scales to the device, so it doesn't look like the component is being cut off of the screen. Sulphine's LinkedIn link is same as Michael's. Long links also break, so it doesn't overflow on phones. Links starting with www links internally so added https.

2022-11-14 22:53 UTC, chalkedgoose commented
@KingMedieval Thank you for your contribution the project you are the first external contribution so 
we haven't bothered to list any requirements for a PR. 

In the future would you mind 
1. Making a more detailed PR title ("UI Fixes" may be hard to grep later down the line)
2. Linking an issue from the project issues panel
3. Including before and after photos of the described changes

2022-11-14 22:56 UTC, charlescohanlon commented on src/pages/contact.tsx
> +            <ContainerLink href="https://linkedin.com/in/charlescohanlon"></ContainerLink>
Thank you, but I've already fixed the broken links.

2022-11-14 22:57 UTC, charlescohanlon commented on src/frontend/components/ResultScrollView.tsx
> +                          }: ResultScrollContainerProps): JSX.Element => {
The ResultScrollContainer cutting off at the bottom was a stylistic choice.

2022-11-14 23:03 UTC, charlescohanlon requested changes

2022-11-14 23:03 UTC, charlescohanlon commented on src/frontend/components/DisplayContainer/ContainerLink.tsx
> +                className={"underline text-blue-600 decoration-blue-600 decoration-2 break-all"}
Would you mind refactoring your PR just to include this change or opening a new one? This is a great suggestion, and I would love to work with you to get it on the codebase.

2022-11-15 03:28 UTC, KingMedieval commented
the latest commit addresses the refactoring you mentioned. Sorry, I'm new to contributing and I am trying to learn github other than using it to host code.

2022-11-15 20:06 UTC, charlescohanlon approved these changes
lgtm!

2022-11-15 20:07 UTC, merged